services:
  - type: web
    name: metadata-extractor
    env: python
    plan: free
    build:
      pythonVersion: 3.10
    buildCommand: pip install -r requirements.txt
    startCommand: streamlit run app.py --server.port $PORT --server.enableCORS false

